# Generated by Django 4.2 on 2023-05-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=50)),
                ('c_des', models.CharField(default='', max_length=500)),
                ('c_img', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Ladeng_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=50)),
                ('page_de', models.CharField(default='', max_length=500)),
                ('page_img', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subCategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('product_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='trending_frame_kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_img1', models.ImageField(default='', upload_to='img')),
                ('p_img2', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='trending_frame_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_img1', models.ImageField(default='', upload_to='img')),
                ('p_img2', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='trending_frame_woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=50)),
                ('p_price', models.IntegerField()),
                ('p_img1', models.ImageField(default='', upload_to='img')),
                ('p_img2', models.ImageField(default='', upload_to='img')),
            ],
        ),
    ]
