# Generated by Django 4.2 on 2023-05-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trending_frame_man',
        ),
        migrations.DeleteModel(
            name='trending_frame_woman',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='p_img1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='p_price',
        ),
        migrations.AddField(
            model_name='product',
            name='p_img2',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mkart.product'),
        ),
        migrations.DeleteModel(
            name='trending_frame_kids',
        ),
    ]
