# Generated by Django 4.2 on 2023-05-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0003_delete_trending_frame_man_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='product_name',
        ),
    ]
