# Generated by Django 4.2 on 2023-05-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0004_rename_p_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='p_name',
        ),
    ]
