# Generated by Django 4.2 on 2023-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0007_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='trending_kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=50)),
                ('p_img1', models.ImageField(default='', upload_to='img')),
                ('p_img2', models.ImageField(default='', upload_to='img')),
                ('p_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='trending_man',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=50)),
                ('p_img1', models.ImageField(default='', upload_to='img')),
                ('p_img2', models.ImageField(default='', upload_to='img')),
                ('p_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='trending_woman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=50)),
                ('p_img1', models.ImageField(default='', upload_to='img')),
                ('p_img2', models.ImageField(default='', upload_to='img')),
                ('p_price', models.IntegerField(default=0)),
            ],
        ),
    ]
