# Generated by Django 4.2 on 2023-06-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0010_alter_c_product_c_des_alter_ladeng_page_page_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_product',
            name='category',
            field=models.CharField(choices=[('Man_tending_page', 'treding_man'), ('Woman_tending_page', 'treding_woman'), ('Kids_tending_page', 'treding_kids'), ('Man', 'man'), ('Woman', 'woman'), ('Kids', 'kids')], default=' ', max_length=50),
        ),
    ]
