# Generated by Django 4.2 on 2023-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0013_alter_c_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_product',
            name='category',
            field=models.CharField(choices=[('man-product', 'man-product'), ('woman-product', 'woman-product'), ('kids-product', 'kids-product')], default=' ', max_length=50),
        ),
    ]
