# Generated by Django 4.2 on 2023-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0014_alter_c_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_product',
            name='category',
            field=models.CharField(choices=[('man-product', 'Man'), ('woman-product', 'woman'), ('kids-product', 'kids')], default=' ', max_length=50),
        ),
    ]
