# Generated by Django 4.2.1 on 2023-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0018_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
