# Generated by Django 4.2.1 on 2023-08-25 04:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mkart', '0019_user_post_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_details',
        ),
    ]
