# Generated by Django 4.2.1 on 2023-08-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mkart', '0022_rename_user_details_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addres',
            old_name='user',
            new_name='user_n',
        ),
    ]
